### PR TITLE
whPullReqTargetRepo can be null

### PR DESCRIPTION
**Pull request by roberth**
**Issue reference:**

**Submission Checklist:**
* [x] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
    - it doesn't say much
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [x] Does your submission pass tests?
* [ ] Have you run lints on your code locally prior to submission?
   - unclear which ones and my change is small
* [ ] Have you updated *all* of the cabal/nix infrastructure?
   - doesn't seem relevant
* [x] Is this a breaking change? Have you discussed this?
   - wrapping a field in `Maybe` is a breaking change, but is required.

### CODE REVIEW

**Comment by kvanbere** [comment]
Thanks Rob for putting the time together to make this pull request.

Admittedly, the infrastructure for this package is in a really bad state right now because we've been flat out for months.

I imagine the scenario is something like, a PR is opened and then the repo is deleted?

Happy to merge.

**Comment by kvanbere** [comment]
I have fixed the broken CI system, would it be possible to rebase so that the checks are run?

**Comment by roberth** [comment]
> I imagine the scenario for this change is something like: a PR is opened and then the repo is deleted?

This seems to be a likely cause but I don't have the data to confirm this, as the fork seems to exist, but may have been recreated. Its occurrence is rare.

**Comment by roberth** [comment]
> would it be possible to rebase

Done, but nothing happened.
You can push to my branch if necessary.

**Comment by kvanbere** [comment]
Thanks, I'll pull this in and work on it from here.

**Comment by roberth** [comment]
> Thanks, I'll pull this in and work on it from here.

I was referring to the "allow edits by maintainers" feature, but what you're doing also works.

Thanks!

**Comment by kvanbere** [comment]
Yeah, sorry, I tried to push into your branch but it was giving me 403 :(

**Comment by roberth** [comment]
Weird. I thought I enabled it. Will pay close attention for next pr.

**Pull request merged**
