### PR TITLE
[#51]: whPullReqTargetRepo can be null (fixes #47)

### PR DESCRIPTION
**Pull request by kvanbere**
**Issue reference:**
#51.

**Submission Checklist:**
* [x] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [x] Does your submission pass tests?
* [x] Have you run lints on your code locally prior to submission?
* [x] Have you updated *all* of the cabal/nix infrastructure?
* [x] Is this a breaking change? Have you discussed this?

### CODE REVIEW

**Comment by kvanbere** [comment]
@roberth shall I add you to `AUTHORS` ?

**Comment by roberth** [comment]
Sure! The more the merrier.

**Comment by kvanbere** [comment]
Ugh, the merge with squash erased the authorship from `9a78a65`. Surely that's not normal, otherwise it's a useless feature.

**Comment by roberth** [comment]
In my experience, git and github work best with merges.

Don't worry about fixing it up.

**Comment by kvanbere** [comment]
This has been released, thanks @roberth!

**Pull request merged**
